# Generated by Django 5.1.7 on 2025-04-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_created_at_task_assigned_by_task_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_name',
            field=models.CharField(default=None, max_length=150, unique=True),
        ),
    ]
