# Generated by Django 5.1.7 on 2025-04-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_customuser_user_name_alter_task_assigned_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_name',
            field=models.CharField(default='default_user', max_length=150, unique=True),
        ),
    ]
