# Generated by Django 5.1.7 on 2025-04-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_remove_customuser_user_name_alter_task_assigned_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_name',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
