# Generated by Django 5.1.7 on 2025-04-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_alter_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='team',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_name',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
    ]
